appsignal/appsignal-python

conftest.py, pyproject.toml, src/appsignal/agent.py, src/appsignal/client.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, tests/test_client.py, tests/test_config.py, tests/test_opentelemetry.py
Here's a test setup PR draft to test this with: https://github.com/appsignal/test-setups/pull/98
I'm making a ton of decisions implicitly, please bikeshed! Should we "auto-detect" instrumentations in this way? Should we still have `disable_default_instrumentations`, or is the dependency opt-in enough?
Commits are a bit too intermingled because I did a lot of changes in one go, sorry.
---
Move things around so that everything that relates to the configuration
options lives in `config.py`. Implement configuration options for
`revision` and `disable_default_instrumentations`, which will be used
in later commits. Allow for the configuration options to be read from
the environment.
When `client.start()` is called, start OpenTelemetry, pointing its
exporter at the agent, which is also started …
=> Start OpenTelemetry

.semaphore/semaphore.yml, script/lint_git
Make sure we follow the same Git styleguide across all integration projects by adding the Lintje Git linter to the project.
Script copy-pasted from the Ruby gem.
https://github.com/appsignal/appsignal-ruby/blob/1fc86ae5a087b3589f91d25f661ef94f459895cd/script/lint_git
Closes #4
=> Add Git linter to the CI build

.changesets/update-agent-6f29190.md, src/appsignal/agent.py, src/appsignal/config.py, src/scripts/agent.py, tests/test_config.py
- Log revision config in boot debug log.
- Update internal agent CLI start command.
- Rename internal `_APPSIGNAL_ENVIRONMENT` variable to `_APPSIGNAL_APP_ENV` to be consistent with the public version.
=> Update agent to version 6f29190

mono.yml
Configure mono for a custom language, as it doesn't directly support Python (yet).
Add scripts to read and update the package version. These will be called by mono, PR https://github.com/appsignal/mono/pull/52.
Part of #3
=> Configure mono for package

src/appsignal/config.py, tests/test_config.py
Makes it easier to edit if everything is sorted alphabetically. We've also done this in the Node.js integration recently.
Allow people to edit the hostname reported for the app.
=> Config hostname

src/appsignal/config.py, tests/test_config.py
Set the language integration version as an env var, rather than a resource attribute. We don't need to the particular use case of the resource attributes here.
Also include the package's version number this way so we know which package version the reported data is sent from.
=> Set the language integration as an env var

.semaphore/semaphore.yml
When we (force) push on a branch, cancel the previous build. This saves time on waiting for the previous build to send, and the next one to start.
The main and develop branch are excluded, because we would like to know if every (merge) commit passes there.
=> Auto cancel builds on Semaphore CI

src/appsignal/config.py
Don't only set the TypeDict to `total=False` to not have to specify all the fields on initialization, but make all fields optional. This allows us to have unset config options like booleans in the future and recognize them by something more clear than an empty string.
This has no influence on the interaction with these optional fields.
=> Make all the config options optional fields

src/appsignal/config.py, src/appsignal/opentelemetry.py, tests/test_config.py
Configure the agent's app path and revision using the env var. This scenario doesn't need it to be configured using the resource attribute. We fully control how the agent is started using the Python package.
The `app_path` config option isn't something people need to configure 99% of time, but let's leave it in for that one edge case and to make it easier to test.
=> Move resource attributes to private env var config

src/appsignal/client.py, src/appsignal/config.py, tests/test_client.py, tests/test_config.py
Add config options that are booleans and should be interpreted as such.
Part of #16
=> Add boolean config options

src/appsignal/config.py, tests/test_config.py
Parse lists from environment variables, and format them again when set as private env vars for the agent.
I left out request_headers, because we should check what the default for that should be in more detail. This is more the general structure of parsing and setting config options that the client does not directly use (right now).
Part of #16
Based on #28
=> Add config options of the list type

src/appsignal/config.py, tests/test_config.py
No parsing needed for these config options. They are not currently used by the package itself, but only configure the agent.
Part of #16
=> Add string config options

src/appsignal/config.py, tests/test_config.py
Don't set the default certs file yet. That's part of issue #30. This
just adds the config option in case anyone wants to override it. The
agent will listen to it.
Part of #16
=> Add ca_file_path config option

src/appsignal/config.py, tests/test_config.py
﻿## Add log_path config option
Check if the specified path is writable or not, and if not, fall back on the system tmp dir.
It just prints the warning and doesn't log it. We don't have an internal logger yet, see issue #34. It will also need to log it eventually.
While discussing this implementation, we decided we want to refactor this so there's a Config class that handles all the function calls, so that we don't need to call `validate` manually this way in the future. See issue #36. So I'm leaving a proper validation "state" in the Config for that issue.
[skip changeset] Part of #16
Use the `gettempdir` method to fetch the system tmp dir. This won't work on macOS the way we want to, because it will create a new tmp dir every time and we want it to point to `/tmp`.
=> Add log_path config option

pyproject.toml, src/appsignal/cli.py, src/appsignal/config.py, tests/test_cli.py
Implement an installation command that asks the user to input the necessary information to generate an `appsignal_config.py` file.
Closes #18. [skip changeset]
The installer is functional, but it's missing "flair" -- emojis, links to the docs, friendliness, that sort of stuff. Suggestions welcome. I could also just copy what some other integration's installer does.
=> Implement install command

src/appsignal/agent.py, src/appsignal/client.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, tests/test_client.py, tests/test_config.py, tests/test_opentelemetry.py
We had a bunch of different Options dict instances that we merged for multiple sources to create the config for the package.
This change merges all config into one class that keeps track of the config options, sources, and potential other state.
Needed for #19, to implement the diagnose report.
Closes #36
=> Refactor config into Config class

src/appsignal/config.py, tests/test_config.py, tests/test_opentelemetry.py
No need to pass in `None` as an argument when no Options need to be set.
They don't need to know anything of the instance state currently, so let's leave it out.
Rather than assign separate fields on the Config class, store all different config sources on the same dictionary so it's easier to find back.
=> Config refactor part 2

src/appsignal/config.py, tests/test_config.py
Add `Config().option("key")` to fetch config options more easily than `Config().options.get("key")`.
I also looked into supporting `__getitem__`, but this gives trouble trying to fetch keys from a TypedDict (the options object) when the key is a variable. It expects a string literal.
=> Add convenience method to fetch config options

src/appsignal/client.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, tests/test_client.py, tests/test_config.py
Allow users to specify an allow list of request headers. Configure the OpenTelemetry instrumentation using the env var. There is no config option on the Django or wsgi/asgi instrumentations to specify it another way, only the env var.
There is a small difference between what you configure and what you see in the AppSignal.com UI. The header name for the `request_headers` config option needs to be using dashes (if the header uses dashes), but it will show up with underscores, because that's how OpenTelemetry exports it.
- Header name: `X-Custom-Header`
- Config: `x-custom-header` (case insensitive)
- Reported name: `x_custom_header`
I hope this won't be too confusing, let's document it properly. And we can always change it later, but this is easiest to implement now.
[skip …
=> Add request_headers config option

.semaphore/semaphore.yml, pyproject.toml, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/scripts/build_hook.py, tests/test_config.py, tests/test_opentelemetry.py
When trying to set up Python 3.8 for the CI and local test suite, it wouldn't load the package files when importing them.
There's a difference in Python 3.8 and 3.9 about the `src` directory for packages. Configure the pythonpath for Python 3.8 so it loads the files properly.
https://stackoverflow.com/a/50156706/543643
[skip changeset] Part of #48
Specify the types using the typing module's variants, rather than the normal list and dict types.
Fixes this error:
```
tests/test_config.py:4: in <module>
from appsignal.config import Config, Options
src/appsignal/__init__.py:1: in <module>
from .client import Client as Appsignal
src/appsignal/client.py:3: in <module>
from .agent import start_agent
src/appsignal/agent.py:6: in <module>
from .config import Config
src/appsignal/config.py:55: in …
```
=> Fix package for Python 3.8

src/appsignal/client.py, src/appsignal/config.py, tests/test_client.py
Allow us to log things to the appsignal.log file.
Add a new "appsignal" logger in Python and configure it to match our logging standard.
https://github.com/appsignal/integration-guide/blob/e0faa6a9e02265b375a449ec6b0f234ccc68834a/build/logging.md
Use the tmp_path helper argument in pytest to create a temporary path to store the log file in for testing.
There is no "trace" level in Python. Not sure how we can support that.
This doesn't implement the STDOUT logger. That's the next step.
Part of #34
=> Add internal logger

src/appsignal/config.py
This currently prints "Unable to write to configured 'None'", which is not what we want.
Quick thing I noticed while looking into the log output issue in #56.
=> Fix log path failure log message

src/appsignal/cli.py
Demo CLI command that sends two sample actions to AppSignal. One standard HTTP one and an error.
The install command now calls the demo command when finishing.
Part of: https://github.com/appsignal/appsignal-python/issues/12
=> Add demo command

src/appsignal/config.py, src/appsignal/opentelemetry.py
Automatically start the Flask instrumentor included in the SDK when starting the AppSignal client.
Part of: https://github.com/appsignal/appsignal-python/issues/9
=> Add Flask integration

conftest.py, src/appsignal/agent.py, tests/test_client.py
The agent_active variable is a global state that doesn't reflect the actual environment of some tests. Reset it between tests so that tests that shouldn't have an active agent, do not.
Make the config actually something the agent can start with. Without the Push API key it doesn't start the agent and fails the test. Not sure how this only failed after merging #56.
=> Fix test suite state

conftest.py
A bunch of tests start, or try to start, the agent with different configs. These can conflict with each other and not start the agent when it is supposed to. A common error I see in the appsignal.log is this:
```
[2023-05-24T11:25:59 (agent) #43777][Debug] Booting appsignal-agent
[2023-05-24T11:25:59 (agent) #43778][Debug] Starting appsignal-agent in daemonized mode
[2023-05-24T11:25:59 (agent) #43778][Debug] Exiting agent, we did not become owner of the lock
[2023-05-24T11:25:59 (agent) #43778][Debug] is_currently_owner: Our pid is Some(43778), pid on disk is Some(43423)
```
Remove the AppSignal working directory before every test. This quickly shuts down the agent and fixes the OpenTelemetry connection error for port 8099 (the agent).
I also tried to make it work with psutil like so, …
=> Make sure agent is stopped before every test

src/appsignal/opentelemetry.py
Parse the query params if present for each request and add them to the request parameters magic attribute.
Closes #62 
=> Add query params to Flask spans

src/scripts/sdist_hook.py
This script should fail, but it failed on a vague error, rather than the intended error on Python 3.11.
```
File "/Users/tombruijn/appsignal/python/src/scripts/sdist_hook.py", line 6, in CustomBuildHook
def initialize(self, version: str, build_data: dict[str, Any]) -> None:
TypeError: 'type' object is not subscriptable
```
=> Fix hatch build script

README.md, mono.yml, pyproject.toml, src/scripts/build_hook.py
[skip changeset] because this is all build script related
When `mono clean` is invoked, the agent binaries should be
downloaded again, in case the agent binary cache was tampered with.
Not sure how this would happen, but we should error if it does.
An argument can be passed to `hatch run build:me` specifying the
path to the agent: `hatch run build:me path/to/agent`.
Additionally, you can use the `--keep-agent` flag to use the current
agent binary that is already present at `src/appsignal/appsignal-agent`
from a previous build: `hatch run build:me --keep-agent`.
The latter can be useful in containerised environments like our test
setups, which mount the integration repository as a volume in a
container, but not the agent repository -- meaning the location of the
agent artifact is not …
=> Allow custom agent builds

src/appsignal/config.py, tests/test_config.py
As discussed in the integrations guide issue https://github.com/appsignal/integration-guide/issues/73 Change the config source load order to use the "initial" config source last.
The environment source can be referenced from the config file and conditional behavior can be set based on it, but the given config to the initializer will be the final used config once merged with the other sources.
New load order:
- Default source (hardcoded config)
- System source (context dependent config)
- Environment source (environment variables)
- Initial source (any config given to `Config()` in `__appsignal__.py`)
=> Load file/initial config options source load

.changesets/bump-agent-to-91f1a7c.md, src/scripts/agent.py
- Fall back on the revision option for OpenTelemetry endpoint from config, rather than only read it from the OpenTelemetry resource attributes.
- Fix agent restart when the config changes, not detecting a config change and not starting a new agent process.
- Retry agent servers port binding when port is busy. This fixes Python package restarting the agent when another agent instance is still running.
[skip review]
=> Bump agent to 91f1a7c

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, SUPPORT.md
Update the README to follow our other project's structure. Add missing files to add a license, Code of Conduct and other files detected by GitHub.
=> Add and update project files

pyproject.toml, src/appsignal/cli/base.py, src/appsignal/cli/command.py, src/appsignal/cli/demo.py, src/appsignal/cli/install.py, tests/test_cli.py
Extract the different CLI functionalities into their own module and classes. This way, the implementation of the Diagnose command will be simpler.
=> Refactor CLI file

.changesets/add-support-for-asgi-frameworks.md, src/scripts/agent.py
Closes #10.
Adds support for ASGI-based frameworks, such as FastAPI and Starlette.
=> Bump agent to version ff454dc

pyproject.toml, src/appsignal/client.py
1. Use config for mypy options, so that the IDE and `hatch run lint:typing` produce the same results. The `--enable-incomplete-feature` flag statys, though, I don't think there is a config option for that.
1. Resolve mypy violation by importing Unpack from typing_extension. You don't need to install typing_extension for that to work, myp ships with stubs for it.
1. Explicitly list mypy dependencies instead of using `--install-types`. Let your package manager deal with packages. It's faster, it's explicit, it's reliable.
=> Mypy config

.gitignore, conftest.py, pyproject.toml, src/appsignal/__init__.py, src/appsignal/agent.py, src/appsignal/cli/base.py, src/appsignal/cli/command.py, src/appsignal/cli/demo.py, src/appsignal/cli/install.py, src/appsignal/client.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/scripts/build_hook.py, src/scripts/sdist_hook.py, tests/test_cli.py, tests/test_client.py, tests/test_config.py, tests/test_opentelemetry.py
[isort](https://pycqa.github.io/isort/) is a code formatter for sorting and grouping python imports. The PR add isort into `lint` dependencies and uses it to sort all imports.
=> Sort all imports using isort

conftest.py
It seems like `os.system` argument
of the fixture is supposed to be an f-string.
Copy of  #92
=> Fix stop_agent fixture

src/appsignal/opentelemetry.py
Specify the OpenTelemetry HTTP exporter should export to `/v1/traces` path so we can more easily differentiate different requests on the HTTP endpoint on the agent.
No agent changes are needed with this agent version, it listens to any and all paths (it ignores the path).
=> Update OpenTelemetry HTTP exporter path

conftest.py, src/appsignal/agent.py, src/appsignal/client.py, tests/test_client.py
Before: agent state is a global variable
managed from a set of functions
using `global`.
After: the agent state is managed by
Agent singleton. The state is incapsulated,
and all related logic shares the same namespace.
The resulting code is shorter and easier to test.
I'd prefer to avoid a global state altogether
and let Client manage the Agent,
but that would require to rethink the tests
that currently implicitly manage
the agent state from autouse fixtures.
=> Refactoring: turn agent wrapper into a singleton

pyproject.toml
Add some configuration options for mypy
making it more strict. I could add `strict = true` instead but that's too strict and some code
fails it. Maybe later.
=> Make mypy configuration more strict

src/appsignal/config.py
These `load_from_*` methods don't need to be class methods. They can be static methods instead as they don't do anything with the rest of the class.
=> Make Config classmethods staticmethods instead

src/appsignal/opentelemetry.py, tests/test_opentelemetry.py
A nitpick on top of #95, restoring typing for the default instrumentation adders. Trying to prevent typos when referring to the default instrumentations (including our own typos!)
@orsinium I'm curious as to whether this makes sense to you, or am I too deep in the TypeScript mindset?
=> Restore literal typing for instrumentations

.changesets/bump-agent-to-32590eb.md, src/scripts/agent.py
- Only ignore disk metrics that start with "loop", not all mounted disks that end with a number to report metrics for more disks.
[skip review]
=> Bump agent to 32590eb

.changesets/report-total-cpu-usage-metric-for-vms.md, src/scripts/agent.py
This change adds another `state` tag value on the `cpu` metric called `total_usage`, which reports the VM's total CPU usage in percentages.
Part of https://github.com/appsignal/probes-rs/issues/64
[skip review]
=> Report total CPU usage host metric for VMs

src/appsignal/cli/diagnose.py
It would print things like `False`, `not started`, and `not writable` for tests that weren't present. This doesn't mean they are not writable, only that we couldn't test it. Most likely because the config wasn't loaded and it didn't know what paths to check.
Fix the format to match the other integrations and print a dash instead.
=> Fix formatting for Python agent tests

.changesets/bump-agent-to-6bec691.md, src/scripts/agent.py
- Improved agent HTTP server for OpenTelemetry traces and metrics.
- Upgrade `sql_lexer` to v0.9.5. It adds sanitization support for the `THEN` and `ELSE` logical operators.
[skip review]
=> Bump agent to 6bec691

.changesets/add-diagnose-command.md, .gitmodules, .semaphore/semaphore.yml, pyproject.toml, src/appsignal/agent.py, src/appsignal/cli/base.py, src/appsignal/cli/diagnose.py, src/appsignal/cli/install.py, src/appsignal/config.py, src/appsignal/push_api_key_validator.py, tests/test_push_api_key_validator.py
This PR includes a diagnose command which can be called through `appsignal diagnose`, a report that can be submitted to AppSignal, and a report that's printed to the terminal. 
This also involves some shortcuts being made so we can work from a passing test suite. So far, the shortcuts made are a couple of hardcoded values, which will be fixed in this pull request, but are moved back for now. I'm listing them here so we're clear on what's not yet implemented, outside of the test failures:
=> Diagnose command

.changesets/warn-if-appsignal-beta-package-is-present.md, src/appsignal/__init__.py
We have renamed the package to `appsignal` in PR #112. Previously, we published the package as `appsignal-beta` because we couldn't publish using the `appsignal` package name.
To encourage people to switch to the `appsignal` package, we will ship a new version of the `appsignal-beta` package that has a dependency on the new `appsignal` package and prints a deprecation warning about the beta package if imported.
This change imports the beta package and prints the deprecation warning. If the package is not found, it will throw an error, which we'll catch and ignore.
Ignore the warnings from the linters about the library not being found.
Part of #111
=> Print deprecation warning if beta package present

.changesets/add-statsd_port-config-option.md, src/appsignal/config.py, tests/test_config.py
Allow users to configure the statsd_port on the appsignal-agent process. This to fix two conflicting servers on the same port.
I had made this before (and checked Python off from the to do list), but never submitted the change 😖
Part of https://github.com/appsignal/appsignal-agent/issues/982
=> Add the statsd_port config option

.changesets/add-opentelemetry-port-config-option.md, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/scripts/agent.py, tests/test_config.py
Allow users to configure the OpenTelemetry HTTP server in the agent to listen on another port.
Part https://github.com/appsignal/appsignal-python/issues/27
Requires an agent update before merge and release.
=> Add opentelemetry_port config option

.changesets/add-role-config-option.md, src/appsignal/config.py, tests/test_config.py
Allow users to configure a role for a host. It's not used a lot in the product yet, but we generate a metric for it and we can do some more stuff with it in the future.
I chose the `host_role` name because `role` alone is a bit ambiguous and the env var is named `APPSIGNAL_HOST_ROLE`.
Part of https://github.com/appsignal/appsignal-agent/issues/1020
=> Add host_role config option

.changesets/fix-cli-run-using-python--m-appsignal.md, src/appsignal/cli/command.py, src/appsignal/cli/demo.py, src/appsignal/cli/diagnose.py
When using `python -m appsignal ...` it would complain about missing imports.
Use relative imports instead, they seem to work for other imports, like `..__about__` in `src/appsignal/cli/version.py`.
=> Use relative imports in the CLI modules

.changesets/bump-agent-to-6133900.md, src/scripts/agent.py
- Fix `disk_inodes_usage` metric name format to not be interpreted as a JSON object.
- Convert all OpenTelemetry sum metrics to AppSignal non-monotonic counters.
[skip review]
=> Bump agent to 6133900

.changesets/enable-opentelemetry-metrics-exporter.md, src/appsignal/opentelemetry.py
Add the metrics exporter by default so users are able to send metrics using OpenTelemetry to AppSignal.
Tracking issue: https://github.com/appsignal/appsignal-python/issues/7
We can set with which temporality metrics are exported. To avoid clashes with cumulative sum conversion to deltas from multiple processes, prefer to send cumulative sums as delta sums.
To make it explicit for all metrics we support, I've added them all the exporter config.
=> Add OpenTelemetry metrics exporter

.changesets/add-counter-metric-helper.md, .changesets/add-gauge-metric-helper.md, src/appsignal/metrics.py, tests/test_metrics.py
Add convenience helper method to report counter metrics using the AppSignal terminology along with all the OpenTelemetry boilerplate.
This doesn't allow for setting units or metric descriptions, which OpenTelemetry supports, because we discard this metadata.
Part of #124
Add convenience helper method to report gauge metrics using the AppSignal terminology along with all the OpenTelemetry boilerplate.
This doesn't allow for setting units or metric descriptions, which OpenTelemetry supports, because we discard this metadata.
This is using the OpenTelemetry ObservableGauge in the background, but exposes an API to what we're used to in other integrations with `set_gauge`.
The ObservableGauge registers a callback that it runs asynchronously in the background every 60 seconds. 60 seconds after …
=> Add metric helpers for counters and gauges

.changesets/add-counter-metric-helper.md, .changesets/add-gauge-metric-helper.md, src/appsignal/__init__.py, tests/test_metrics.py
Like the tracing helpers, export the metrics helpers on the root so it doesn't have to be imported from `appsignal.metrics`.
[skip changeset] as it modifies an unreleased change.
=> Export metric helpers in root module

src/appsignal/metrics.py, tests/test_metrics.py
We support these other types as tag values, so let's update the type definition to allow it.
[skip changeset] as it's an improvement on a not yet released feature.
=> Update tag value types to support int, float, bool

.changesets/bump-agent-to-e8207c1.md, src/scripts/agent.py
- Add `memory_in_percentages` and `swap_in_percentages` host metrics that represents metrics in percentages.
- Ignore `/snap/` disk mountpoints.
- Fix issue with the open span count in logs being logged as a negative number.
- Fix agent's TCP server getting stuck when two requests are made within the same fraction of a second.
[skip review]
=> Bump agent to e8207c1

pyproject.toml
pypi has a classifier to indicate which state of development a package is in. We're beyond alpha, and ready to be used in production apps. Let's classify as such.
[skip changeset] as it's a metadata change we don't need to release a new version for. It can be included in the next release.
=> Bump package classifiers to stable

.changesets/fix-agent-diagnostic-report-in-diagnose-cli-tool.md, src/appsignal/agent.py, src/appsignal/cli/diagnose.py, tests/cli/test_diagnose.py
The diagnose CLI tool did not configure the agent diagnose run with the configuration. As a result it would always fail the agent diagnose tests.
Set the private env vars using the `Config.set_private_environ` method and update the subprocess run of the agent with the `--private` flag to read the right private environment variables format.
Fixes #141
Based on #148 
Related diagnose tests PR: https://github.com/appsignal/diagnose_tests/pull/96
=> Fix diagnose loading config for agent diagnose

.changesets/validate-config-before-starting.md, src/appsignal/cli/demo.py, src/appsignal/config.py, tests/cli/test_demo.py, tests/test_config.py
Add the missing test for the demo CLI. It only tests if the config is valid or not, as testing if the OpenTelemetry span creation works is not necessary I think for now. It will require a lot of mocking, which doesn't tell us if the code actually still works or not.
I've also updated the config validation to not print an error immediately on validation. This may also be printed in some scenarios we don't want.
Preferably this is logged to the `appsignal.log` file like in the Ruby integration, but here we don't have a logger instance yet in the Python package. Something to improve later.
The demo CLI will log that the config is invalid, which can be debugged with the diagnose CLI if needed. The normal client start already logged a message when it couldn't start.
Needed for #138
=> Add demo CLI test and remove validate output

.changesets/add---environment-cli-option-to-demo-cli-tool.md, src/appsignal/cli/command.py, src/appsignal/cli/demo.py, src/appsignal/cli/install.py, src/appsignal/config.py, tests/cli/test_demo.py
Move the empty line print to the install CLI so that the demo CLI doesn't start with an empty line. Update the tests to match.
Instead of defining some defaults in the main CLI class, explicitly define them per CLI command, so it's easier to customize the CLI options per command.
Allow users to specify which environment they want to send the demo samples for. Normally it defaults to the `development` environment.
For the install CLI (which calls the demo CLI), it will continue to default to the development environment like our other integrations.
Part of #138
---
Based on #146
=> Add demo CLI --environment option

.changesets/load-__appsignal__-py-file-in-demo-cli.md, src/appsignal/cli/demo.py, src/appsignal/cli/install.py, tests/cli/test_demo.py, tests/cli/test_install.py
Create the demo samples in its own class, separate from the configuration. This makes it more easily called by other parts of the package, like the install CLI.
The install CLI will configure the client on its own, as it uses different arguments than the demo CLI. Passing the CLI arguments along will cause an error if the demo if it calls demo CLI specific arguments that aren't part of the install CLI.
When the demo CLI finds a `__appsignal__.py` configuration file, use that for the configuration, rather than only rely on the CLI prompt.
The demo CLI will overwrite the `active` config option to always be true when loading the file config.
One install test failed, because it expects a real file to be present and I didn't want to add more mocking to account for that. Instead, it now doesn't …
=> Load __appsignal__.py file when found in demo CLI

tests/cli/test_demo.py, tests/cli/test_diagnose.py
Use `"str" in variable` to find substrings, rather than use the more verbose `variable.find("str")` method.
[skip review]
=> Update substring assertions in tests

.changesets/add-set_sql_body-tracing-helper.md, .changesets/bump-agent-8260fa1.md, src/appsignal/__init__.py, src/appsignal/tracing.py, src/scripts/agent.py, tests/test_tracing.py
Make it easier to set SQL queries as the span body attribute without danger of storing unsanitized SQL queries.
When `set_sql_body` is used in combination with `set_body`, the `set_sql_body` call is leading.
Part of https://github.com/appsignal/appsignal-python/issues/140
Required agent PR: https://github.com/appsignal/appsignal-agent/pull/1067
=> Add set_sql_body tracing helper

src/appsignal/cli/install.py, tests/cli/test_install.py
In the install CLI we had an almost identical code to the PushApiKeyValidator module present. I've updated it to use the PushApiKeyValidator module instead so we don't have a bunch of duplicate code.
Change the test to expect a POST request, instead of a GET request. The API doesn't care which HTTP request method is used, it listens to both type of request methods.
[skip changeset] as it's an internal change with no user visible change.
=> Refactor Push API key validation in install CLI

.changesets/fix-agent-diagnostic-report-in-diagnose-cli-tool.md, .changesets/load-__appsignal__-py-file-in-demo-cli.md, src/appsignal/cli/demo.py, src/appsignal/cli/diagnose.py, src/appsignal/client.py, tests/cli/test_demo.py, tests/cli/test_diagnose.py
Move the logic of loading the app's client file to the Client class. This makes it easier to reuse by other CLIs, like the diagnose tool.
When the diagnose CLI finds a `__appsignal__.py` configuration file, use that for the configuration.
Before, it relied on the default sources and environment variables, but there was no other way to load the configuration in the diagnose report.
Update the existing changeset, as it basically covers the same material, but for another CLI tool now too.
Closes #142
=> Load __appsignal__.py file when found in diagnose 

.changesets/fix-push-api-key-validation.md, src/appsignal/cli/command.py, src/appsignal/cli/install.py
The configuration obtained from the installer prompts was not being passed correctly to the installer.
Fixes #161.
=> Fix push API key validation on installer

.changesets/fix-diagnose-report-error-when-a-path-was-not-found.md, .changesets/print-more-path-details-in-diagnose-cli-output.md, src/appsignal/cli/diagnose.py, tests/cli/test_diagnose.py
This change was originally prompted by the bug reported in #158. If the `appsignal.log` file could not be found, it would exit with an error when trying to read the log file.
While fixing this, I noticed the paths subreport didn't print the same output as other integrations. While fixing this I refactored how the paths subreport is generated, which also includes the fix. It was more work to split the fix out or fix it first, than include it in the refactor.
The fix is to early return from the method doing all the information gathering about a path (directory/file) when it does not exist with this if-statement in the `PathsReport._path_metadata` method:
```python
if not info["exists"]:
return info
```
The refactor moves the paths data gathering to a new PathsReport class for better …
=> Fix and improve diagnose paths report output

.changesets/_release-1-0.md
Nothing in this release requires a major version bump, but as discussed, we are ready to release version 1.0 to communicate it's ready for use.
It's not feature complete: we don't have Python logging integration for example, but those features will be added a later time.
I created a small changeset that kind of summarizes what the package contains now, but this is not meant to replace the blog post announcement and we should update the changelog later to link to that instead. This is there now in case we release before a blog post is out.
The changeset file name starts with an underscore to hopefully put it on the top upon release.
---
This doesn't have to get merged right away. We can decide upon a good moment to merge it.
=> Bump package to version 1.0

.changesets/fix-demo-error-and-performance-incidents.md, .changesets/rename-example-error-reported-by-our-installer-and-demo-clis.md, src/appsignal/cli/demo.py
To display the demo samples message for the first error reported by our integration, fix how the `demo_sample` tag is set.
It should be set as a tag, using the magic attribute, not by directly setting an OpenTelemetry span attribute.
We reported the demo error as a ValueError, which is a normal error in Python. This might have people think something is wrong immediately. Use the custom `DemoError` class to communicate that it's just an example error. This matches how we report this error name in other integrations.
=> Fix the demo samples recognition and use a custom DemoError class

.changesets/add-warning-to-client-file.md, src/appsignal/cli/install.py, tests/cli/test_install.py
When we generate an `__appsignal__.py` file in the install CLI, also add a message about not committing this key to Git, but move it to some other system instead.
=> Add push API key message to client file template

src/appsignal/cli/demo.py
Report the error using our own `set_error` helper, rather than the OpenTelemetry way. This makes it more consistent how the sample data is set for all samples in for the demo module.
[skip changeset] it's an internal change we release whenever we want.
=> Use the `set_error` helper in the demo CLI

CHANGELOG.md
Link to the blog post that goes into more detail about the release.
---
[skip review]
=> Update CHANGELOG with link to blog post for v1.0

.changesets/report-agent-architecture-and-platform-in-diagnose-report.md, .gitignore, mono.yml, src/appsignal/agent.py, src/appsignal/cli/diagnose.py, src/scripts/build_hook.py
The `mono clean` command would fail when the `appsignal-agent` file did not exist. Add the `-f` flag to ignore that if it doesn't exist.
We ship a separate package for every architecture and platform. The agent isn't installed upon package download/install, like in other integrations.
By adding the agent's architecture and platform, we know which package version was installed for which architecture and platform. Ship a `_appsignal_platform` file in the distributed package, which is then read by the diagnose CLI. I don't want the diagnose CLI to detect the host here, I want to know which release artifact (as pushed to pypi) was installed.
=> Report agent architecture and platform in diagnose

.changesets/report-the-package-install-path-in-the-diagnose-report.md, src/appsignal/cli/diagnose.py
This will help debug path related issues in the diagnose report viewer.
Using the same technique I found in `src/appsignal/agent.py` to fetch the current file's path, but then navigate up twice to get the package's path.
=> Add package install path to the diagnose report

.changesets/bump-agent-to-b604345.md, .changesets/report-running_in_container-in-diagnose-report.md, src/appsignal/cli/diagnose.py, src/scripts/agent.py
I've updated the agent to report the `running_in_container` field in the agent's diagnose report's `host` sub report.
In the Python package I've copied it to the host sub report on the main diagnose report as well. That way the diagnose viewer has to less about where this field is originates from for every integration. It will report this field for the agent report, as for all other integrations, but that won't get in the way. We can even hide it in the viewer.
Part of https://github.com/appsignal/appsignal-python/issues/172
⚠️ Requires agent update in https://github.com/appsignal/appsignal-agent/pull/1073 to make the build pass.
=> Report running_in_container in diagnose report

.changesets/bump-agent-1dd2a18.md, src/scripts/agent.py
- When adding an SQL body attribute via the extension, instead of truncating the body first and sanitising it later, sanitise it first and truncate it later. This prevents an issue where queries containing very big values result in truncated sanitisations.
[skip review]
=> Bump agent to 1dd2a18

.changesets/fix-demo-samples-metadata.md, src/appsignal/cli/demo.py
Remove unused `http.method` attributes. They would appear in the "Attributes" box in the UI that only shows up for root span attributes we don't know what to do with.
Set the category for the performance sample so the event timeline doesn't show an "unknown" event.
Removing the `otel.instrumentation_library.name` attribute because it's not needed. It will use the root span's "GET /demo" name by default.
Fixes #168
=> Fix demo CLIs samples metadata

.changesets/fix-crash-diagnose-report-platform.md, pyproject.toml, src/appsignal/agent.py, src/appsignal/cli/diagnose.py, src/scripts/build_hook.py
Intercom conversation: https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700274092#part_id=comment-16410700274092-21909541622
The platform file should never be missing. But if it somehow is, then don't crash the diagnose report because of it.
Fix a typo in the name of the function that reads from the platform file.
If the platform file is missing from our agent build cache, make sure that we do not consider that to be a correct build. Downloading the agent again is overkill, but it does the trick.
Ensure the platform file is actually added by declaring it as a build artifact.
=> Fix missing platform file error

.changesets/error-metrics.md, src/scripts/agent.py
Fixes issue with error metrics for apps like Node.js Koa. Could affect Python spans as well.
[skip review]
=> Bump agent to 8f31b1a

.semaphore/semaphore.yml
Not sure why we were installing it with `sudo` but that broke the `sem-version python 3.11` setting, and ran the linter under Python 3.8 (the system default) instead.
Remove `sudo` from the command so the linter runs in the Python version we configure.
Because some jobs override the Python version set in the global prologue, move it to each individual job to avoid confusion.
Amend the CI config to print the versions of the dependencies that are installed when the Hatch env is initialised.
=> Remove sudo from CI install command for hatch

.github/workflows/ci.yml
There's a bug or something on the scheduled build, so skip it for now.
Following the docs:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
[skip review]
=> Skip Git linter on scheduled event

src/appsignal/cli/base.py, src/appsignal/cli/command.py, src/appsignal/cli/config.py, src/appsignal/cli/demo.py, src/appsignal/cli/diagnose.py, src/appsignal/cli/exit_error.py, src/appsignal/client.py, tests/cli/test_demo.py, tests/cli/test_diagnose.py
When reading the `__appsignal__.py` configuration file from the demo or diagnose command, handle unexpected errors in the file (e.g. syntax errors) instead of only handling the expected error of the `appsignal` variable being missing.
Unify the handling of errors when reading a config file. Provide an `ExitError` that can be raised by command helpers to trigger the command to exit.
Since loading the configuration file is only done by the diagnose and demo commands, move that functionality out of the `Client` file and into a helper for the CLI commands.
=> Catch unexpected errors reading config file

.changesets/add-distribution-value-custom-metric-helper.md, pyproject.toml, src/appsignal/__init__.py, src/appsignal/metrics.py, src/appsignal/opentelemetry.py, tests/test_metrics.py
Add an `add_distribution_value` custom instrumentation metrics method, in the same line as the ones that currently exist for Ruby, Elixir and Node.js.
To do
---
=> Add `add_distribution_value` method

.changesets/add-minutely-probes-system.md, conftest.py, src/appsignal/client.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/appsignal/probes.py, tests/test_probes.py
Implement a minutely probes system, heavily borrowing from the one
in our Ruby integration.
Implement a config option that globally enables or disables the
minutely probes system, in line with our other integrations.
When disabled by the config option, the minutely probes system can
still be manually enabled by calling `appsignal.probes.start()`.
Ensure that calling this function multiple times will not result in
the probes running multiple times per minute.
Add a lock around registering, unregistering and executing probes
to prevent race conditions where e.g. a probe's unregistering takes
place halfway through its execution.
These functions are already in the `appsignal.opentelemetry` method,
they do not need to have `_opentelemetry` in their name.
Got in a bit of a pickle to make the …
=> Implement minutely probes

src/appsignal/cli/install.py
This is a sequel to #200 that I, uh, kinda forgot to do.
---
Add a warning emoji whenever manual instrumentation is required,
that is, always.
For Django's instructions, refer to the modification needed as a
generic "your entrypoints" and leave it for the docs to explain
further.
Change other instructions to use `import appsignal`, replacing the
use of `from __appsignal__ import appsignal`.
I am not sure exactly why this change is needed now. I think Hatch
[added support for specifying custom build hook dependencies][oops]
directly in the custom build hook in the last release, and this
might have accidentally broken the way in which we used to specify
this dependency.
It might also be that the breakage is intentional, in which case
they [forgot to update the docs][whoopsie].
[oops]: …
=> Modify installation instructions to use `import appsignal`

.changesets/add-extractor-for-apollo-gateway.md, .changesets/fix-asgi-events-showing-up-in-the--slow-api-requests--panel.md, .changesets/implement-cpu-count-configuration-option.md, src/appsignal/config.py, src/scripts/agent.py, tests/test_config.py
Remove changesets from the agent that are not relevant to the Python
integration.
Implement the `cpu_count` (`APPSIGNAL_CPU_COUNT` environment variable)
configuration option for the AppSignal for Python integration.
=> Bump agent and implement CPU count

conftest.py, src/appsignal/client.py, src/appsignal/heartbeat.py, src/appsignal/internal_logger.py, src/appsignal/opentelemetry.py, src/appsignal/probes.py, src/appsignal/tracing.py, tests/test_client.py, tests/test_internal_logger.py
Found myself needing to do some of this (the OpenTelemetry part, specifically, for the SQLAlchemy instrumentation) and wishing (earlier on, for the heartbeats and probes) that I did not have to initialise a logger instance in order to log something, and that a genuine trace-level logging option was available.
[skip changeset] because none of this really changes anything for customers (who should not be using `"trace"`)
The logger was kind of "bolted on" to the client class -- when other
parts of the code wanted to use it, they needed to fetch the logger
with the same name separately and deal with it as a variable.
Move this to a separate `internal_logger` module which is initialised
on-demand from the existing initialised (not necessarily started!)
global client.
Make it possible to …
=> Internal logging improvements

.changesets/add-sqlalchemy-and-sqlite-extractors.md, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/scripts/agent.py
See [test setup](https://github.com/appsignal/test-setups/pull/203) and [extractors](https://github.com/appsignal/appsignal-agent/pull/1137). Part of appsignal/appsignal-python#11.
Add SQLAlchemy to the list of instrumentations that are automatically set up when their dependency is present.
Add SQLite3 and Psycopg (which is version 3.x of `psycopg2`)  to the list of instrumentations that are automatically set up when their OpenTelemetry dependency is present.
=> Add SQLAlchemy and database instrumentations

.changesets/python-database-adapters.md, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/scripts/agent.py
See [test setup](https://github.com/appsignal/test-setups/pull/204) and [agent extractors](https://github.com/appsignal/appsignal-agent/pull/1142).
Add support for `aiopg`, `asyncpg`, `mysql`, `pymysql` and `mysqlclient`.
[skip changeset] as the agent bump will carry it.
=> Add Python SQL database adapters

tests/test_tracing.py
Newer versions of the OpenTelemetry API use the full qualified name of the error type, instead of just the name of the error class.
Update our assertions on the tests for the `set_error`, `send_error` and `send_error_with_context` helpers accordingly.
=> Use qualified error type name

.changesets/add-noop-mode-for-unsupported-systems.md, src/appsignal/agent.py, src/appsignal/client.py, src/scripts/build_hook.py, src/scripts/platform.py
Add wildcard triple for unsupported systems
The `any` tag is now installed when downloading the package from an unsupported system.
Don't start components when on unsupported arch
When trying to run the agent, OpenTelemetry and probes on an unsupported system (any-any), prevent the three of them from starting.
Closes #179
=> Add noop mode for unsupported systems

.changesets/add-support-for-pika.md, src/appsignal/config.py, src/appsignal/opentelemetry.py
Add instrumentation support for Pika messages. The global messaging extractor already covers the cases this instrumentation adds, so there's no need for a specific extractor so far.
Action with message production:
Consumption action automatically instrumented
Part of: #181
=> Add support for Pika

.changesets/new-helper-to-manually-stop-all-agent-processes.md, src/appsignal/client.py, tests/test_client.py
In some specific contexts such as serverless functions, the execution is stopped before the agent gets all the data to send it to AppSignal.
There's a new function that manually allows you to gracefully stop AppSignal's agent processes so all the data is flushed before the execution is closed.
Fixes: #221
=> Add helper to manually stop agent processes

.changesets/simplify-the-implementation-of-set_gauge.md, pyproject.toml, src/appsignal/metrics.py, tests/test_metrics.py
The `set_gauge` now uses OpenTelemetry's newer helper, which creates a sync gauge.
Our own implementation of `create_gauge` around the async OpenTelemetry's implementation has been removed in favor of the newer sync helper.
Closes #220
=> Simplify the impementation of the `set_gauge` helper

.github/workflows/ci.yml
Trigger CI builds on new PR creation. This also allows us to run the CI for PRs from forks.
The main and develop branch will also run when pushed.
[skip review]
=> Update config for CI

pyproject.toml
Lock `ruff`, `black`, `isort` and `mypy` to the latest version. We should update these from time to time.
=> Lock linters to latest version

.changesets/fix-scheduler-stop.md, src/appsignal/client.py, tests/test_client.py
When `appsignal.stop()` is called on the AppSignal client, it should call `scheduler.stop()` to stop the scheduler, killing the thread and allowing for the application to finish.
Fixes #233.
=> Call `scheduler.stop()` when AppSignal stops

.changesets/remove-redundant-cron-check-in-pairs.md, src/appsignal/check_in/event.py, src/appsignal/check_in/scheduler.py, tests/check_in/test_event.py
See https://github.com/appsignal/appsignal-ruby/pull/1407 for context. This commit reimplements that in Python.
Before submitting a batch of cron check-in events, check for any pairs of events that are redundant with other pairs of cron check-in events. This would happen, for example, when running a `cron` block for a given identifier many times in quick succession.
A redundant pair of cron check-in events is a pair of start and finish cron check-in events for a given identifier, given that another pair of start and finish check-in events exists for that identifier.
=> Remove redundant cron check-in pairs

.changesets/add--nginx_port--configuration-option.md, src/appsignal/config.py, src/appsignal/opentelemetry.py, tests/test_config.py
**⚠️ This PR cannot be merged until a release of the agent containing appsignal/appsignal-agent#1275 has been released and its agent file merged into this repository. ⚠️** 
Implement an `nginx_port` configuration option that is passed on to the agent, like the existing `statsd_port` and `opentelemetry_port` configuration options.
=> Add `nginx_port` configuration option

src/appsignal/opentelemetry.py
This commit reverts 3cfb6956ac9bea6eb20d4d180af5af03555b0d1f -- the underlying cause was [a bug in the previous OpenTelemetry release][bug] that has been [fixed in the latest release][fix]
[bug]: https://github.com/open-telemetry/opentelemetry-python/issues/4615#issuecomment-2946177912
[fix]: https://github.com/open-telemetry/opentelemetry-python/pull/4618
=> Remove `type: ignore` annotation

src/appsignal/client.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, tests/test_config.py
This is work I realised needed doing while working on documenting the configuration options for the [collector endpoint PR](https://github.com/appsignal/appsignal-python/pull/247).
See https://github.com/appsignal/diagnose_tests/pull/142 for diagnose tests update.
---
Implement the following configuration options in the integration, mapping to the collector-supported, `appsignal.config.`-prefixed resource attribute of the same name:
- `filter_attributes`
- `filter_function_parameters`
- `filter_request_query_parameters`
- `filter_request_payload`
- `response_headers`
- `send_function_parameters`
- `send_request_query_parameters`
- `send_request_payload`
Additionally, also map the following existing configuration options in the integrations to resource attributes in the same manner:
- …
=> Add collector attributes config options
