appsignal/appsignal-python

mono.yml
See appsignal/mono#57 for context.
=> Add `version_scheme` to Mono config

src/appsignal/cli.py
The installation command checks for the presence of supported web frameworks to add the OpenTelemetry instrumentation dependencies if needed and to display a custom output with brief instructions about the detected framework if it requires it.
Closes #43 
=> Check for dependencies when installing

src/appsignal/cli.py, tests/test_cli.py
When the install command is run and the user inputs an API key, it makes a request to AppSignal to validate it. If it's not valid, the installer aborts with a message.
Closes #42
=> Validate Push API key when installing

.changesets/bump-agent-to-8cb4ef2.md, src/scripts/agent.py
This includes the fix for #72 ([agent PR](https://github.com/appsignal/appsignal-agent/pull/1001))
=> Update agent to version 8cb4ef2

src/appsignal/agent.py, src/appsignal/cli/command.py, src/appsignal/cli/demo.py, src/appsignal/cli/install.py, src/appsignal/client.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/scripts/build_hook.py
I noticed that quite a few type annotations are missing. This PR adds the easiest ones: None return type. I'll bring more after this PR is merged.
=> Annotate None return type

pyproject.toml, src/appsignal/cli/base.py, src/appsignal/cli/demo.py, src/appsignal/cli/install.py, src/appsignal/config.py, src/appsignal/opentelemetry.py, src/scripts/build_all.py, src/scripts/build_hook.py, tests/test_opentelemetry.py
1. Add all missed type annotations.
1. Require all functions to be annotated. Now, if an annotation is missed, mypy will fail.
=> Annotate everything

pyproject.toml, src/appsignal/cli/install.py, src/appsignal/client.py, src/appsignal/config.py, src/scripts/build_all.py, src/scripts/build_hook.py, tests/test_opentelemetry.py
1. Enable all ruff rules that don't cause any trouble in the current code.
2. Resolve the reported violations.
=> Make ruff configuration more strict

.changesets/use-render_git_commit-as-revision.md, src/scripts/agent.py
See also https://github.com/appsignal/appsignal-docs/pull/1370, which should have `since_notes` with the versions in which this behaviour was added.
---
Update the agent to a version that supports `RENDER_GIT_COMMIT`, and add a changelog to that effect.
=> Add `RENDER_GIT_COMMIT` support

.changesets/bump-agent-d789895.md, src/scripts/agent.py
- Increase short data truncation from 2000 to 10000 characters.
[skip review]
=> Bump agent to version d789895

.changesets/cgroups-v2-cpu-stats-normalization.md, src/scripts/agent.py
Normalize cgroups v2 CPU stats.
=> Bump agent to eec7f7b

.changesets/update-probes-0.5.4.md, src/scripts/agent.py
- Update probes library with fix for Alpine Linux disk usage stats.
[skip review]
=> Bump agent to bfe19b1

.changesets/cgroups-v1-cpu-percentage-normalization.md, .changesets/cgroups-v2-fractional-cpu.md, src/scripts/agent.py
=> Bump agent to version 0.33.0

.changesets/add-opentelemetry-histogram-support.md, src/scripts/agent.py
=> Bump agent to version 0.33.1

.changesets/support-kamal-based-deployments.md, src/scripts/agent.py
=> Bump agent to version 0.35.10

.changesets/add-opentelemetry-messaging-support.md, .changesets/rename-hostname-tag-to-request_host.md, src/scripts/agent.py
=> Bump agent to version 0.35.12

.changesets/fix-redis-events-misidentified-as-http-events.md, src/scripts/agent.py
=> Bump agent to version 0.35.16

.changesets/add-pika-extractor.md, src/scripts/agent.py
=> Bump agent to version 0.35.17

.changesets/change-primary-download-mirror.md, src/scripts/agent.py
=> Update agent to version 0.35.26

.changesets/set-app-revision-config-option-for-scalingo-deploys.md, src/scripts/agent.py
=> Update agent to version 0.35.27

.changesets/fix-a-performance-issue-when-sanitising--insert-into-----values--queries.md, src/scripts/agent.py
=> Update agent to version 0.35.29

.changesets/remove-opentelemetry-beta-feature.md, .changesets/sanitize-opentelemetry-semantic-conventions-database-attributes.md, src/scripts/agent.py
=> Update agent to version 0.36.0

.changesets/improve-sql-sanitisation.md, src/scripts/agent.py
=> Update agent to version 0.36.2

.changesets/allow-overriding-extractor-namespaces.md, src/scripts/agent.py
=> Update agent to version 0.36.5

.changesets/add--nginx_port--configuration-option.md, src/scripts/agent.py
=> Update agent to version 0.36.6
